### ISSUE TITLE
Ad Code Experiments are highly redundant and need cleanup

### ISSUE THREAD

**Issue by bwnodak** [cafemedia/eng-rfc#1]
.

**Comment by bwnodak** [comment]
@abbydorso @Zureka @theandypeterson would love your thoughts if you have some. 

@Zureka i think you expressed some interest in this area. Is this proposed solution compelling to you or completely overwrought?

**Comment by Zureka** [comment]
I like the proposed idea, but there are a few things I would like to point out:

### Default Results

Including a `defaultResult` value to each entry in the experiment config doesn't make sense, considering the current `default` that we specify in the Experiment classes only uses that default value if the experiment config doesn't have an entry for the specified key.

### The Experiments Class

I like the idea of having a single class from which to fetch experiment results, but I want to make sure that the results of each experiment are calculated once the Experiments class is constructed.

Also, I think the approach of `experiments.get('some-experiment-key').result` could likely lead to errors from spelling mistakes such as `'some-experimet-key`. I don't know if there is an easy way to know the available experiment keys during compile time, but that might be something we could look into.

### AB Group Reporting

Currently, we have a handful of experiments that override the `setABGroup` method to either prevent setting a value for this experiment or override the value that is eventually set. For example, the `HemSourceAllowlistExperiment` result is a long list of allowed HEM sources, and we don't want to include that in our AB Group reporting. Do you have some ideas about how to include this behavior in the new Experiments class?

### Implementation Strategy

You highlighted the potential risks of doing this cleanup in stages, but I truly think that is a less risky approach than the "all at once" option. Perhaps this could be done in stages similar to the BrowserStorage migration. 

1. Introduce the Experiments class
2. Start removing `*Experiment` classes in batches, migrating over to the Experiments class
3. Each batch would have its own ticket, and we could run EA and a quick round of DA (perhaps 2 days instead of 4) to verify things are relatively flat as a result
4. Repeat steps 2 & 3 until migration is complete

### Experiment Cleanup

We currently have in-progress initiatives to clean up or remove old/unnecessary experiments from the current experiment configuration and ad code. It sounds like your proposed approach with the Experiments class would make these easier to remove in the future when we determine they are no longer needed, but I would like to hear your thoughts on that as well.
